### ISSUE TITLE
ODrive could not open UART port

### ISSUE THREAD

**Issue by atuka1998** [Framework-Robotics-GmbH/odrive-ros2-node#1]
Hello. I'm using ROS2 Foxy on my laptop with Ubuntu 20.04. When I try to launch the node, it gives me error: ODrive could not open UART port. I want to use it using USB communication. Could you please tell me any solution? Thank you!

**Comment by HusamZain** [comment]
@atuka1998 I'm having the same issue , Did you find out how to solve it ?
